### PR TITLE
added upcoming reservation logic and fixed swipe refresh

### LINKED ISSUE #108: quick reservation - display upcoming reservation

### PR DESCRIPTION
**Pull request by Yarin18**

### CODE REVIEW

File: composeApp/src/androidMain/kotlin/com/wisemen/chargehub/Util.kt [hunk 1]
```diff
@@ -67,3 +67,15 @@ fun calculateAndFormatDuration(startDateTime: LocalDateTime, endDateTime: LocalD
     return "${hourFormat}:${minuteFormat}"
 }
 val now = Clock.System.now().toLocalDateTime(TIMEZONE)
+
+fun calculateTimeUntilStart(date: LocalDateTime) : String {
+    val now = Clock.System.now().toLocalDateTime(TIMEZONE).date
+    val check = date.date
+
+    val display = when (val daysUntil = now.periodUntil(check).days) {
```
Comment (DanneD-Wisemen) [inline composeApp/src/androidMain/kotlin/com/wisemen/chargehub/Util.kt]: Try and create a pluralStringResource like this:
```
 <plurals name="delivery_estimation">
        <item quantity="zero">Vandaag geleverd</item>
        <item quantity="one">Geleverd in 1 dag</item>
        <item quantity="other">Geleverd in %d dagen</item>
    </plurals>
```

**Review by DanneD-Wisemen — CHANGES_REQUESTED** [review]

**Review by DanneD-Wisemen — APPROVED** [review]
